server:
  port: 8083
  
spring:
  application:
    name: gateway2
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
         

          