spring:
  application:
    name: notification
  
  config:
    import: optional:configserver:http://localhost:8083
    
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-consumer-group-id
      auto-offset-reset: earliest
    producer:
      retries: 0
    template:
      default-topic: my-topic


eureka:
#  instance:
#    hostname: localhost
  client:
#    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
server:
  port: 9093 